project 'Go Kaart!!!.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Go Kaart!!' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Go Kaart!!
  #pod 'DO-Swift'
  pod 'AWSS3'
  
end
